CREATE TABLE jat_jobs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    job_id VARCHAR2(50),
    role_name VARCHAR2(100) NOT NULL,
    job_description CLOB,
    application_date DATE,
    status VARCHAR2(50),
    location VARCHAR2(100),
    salary_range VARCHAR2(50),
    notes CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_jat_user_job FOREIGN KEY (user_id) REFERENCES jat_users(id)
);
